services:
  db:
    image: mysql:8.0
    container_name: mysql_db_samir
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pulseboard_main
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3305:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
