services:
  db:
    image: mysql:8.0
    container_name: mysql_db_samir
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pulseboard_main
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3305:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_samir
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - db
      